Revert "Bugs 2547 & 6890 fixed: Improve EPS/PS export (SansSerif/Serif strings are now exported as Postscript strings and too small marks are exported as circle)"
Does not compile under Mac OS X:
    [javac] /Users/couvert/git/scilab_5.4/scilab/modules/graphic_export/src/java/org/scilab/modules/graphic_export/Export.java:803: cannot find symbol
    [javac] symbol  : method processShape(java.awt.Shape)
    [javac] location: class org.apache.xmlgraphics.java2d.ps.PSDocumentGraphics2D
    [javac]                             return super.processShape(s);
    [javac]                                         ^
    [javac] /Users/couvert/git/scilab_5.4/scilab/modules/graphic_export/src/java/org/scilab/modules/graphic_export/Export.java:787: method does not override or implement a method from a supertype
    [javac]                         @Override
    [javac]                         ^
    [javac] /Users/couvert/git/scilab_5.4/scilab/modules/graphic_export/src/java/org/scilab/modules/graphic_export/Export.java:935: cannot find symbol
    [javac] symbol  : method processShape(java.awt.Shape)
    [javac] location: class org.apache.xmlgraphics.java2d.ps.EPSDocumentGraphics2D
    [javac]                             return super.processShape(s);
    [javac]                                         ^
    [javac] /Users/couvert/git/scilab_5.4/scilab/modules/graphic_export/src/java/org/scilab/modules/graphic_export/Export.java:919: method does not override or implement a method from a supertype
    [javac]                         @Override
    [javac]                         ^
    [javac] 4 errors
    [javac] 14 warnings


This reverts commit f2efd2bd0db8f64f94889347f1206025045576fc

Change-Id: Ia894ff7eeadbc71cabc9e22c09b4efc1099e50be