Revert "Fix modelica compilation:"
I got somme issue after this commit :

[davidcl@paros scicos (5.4)]$ make depend
src/translator/exceptionHandling/exceptHandler.ml
File "src/translator/exceptionHandling/exceptHandler.ml", line 29, characters 21-50:
Error: Unbound module Instantiation
make: *** [src/translator/exceptionHandling/exceptHandler.mli] Erreur 2
[davidcl@paros scicos (5.4)]$ make depend
src/translator/translation/libraryManager.ml
File "src/translator/translation/libraryManager.ml", line 29, characters 18-29:
Error: Unbound module Lexer
make: *** [src/translator/translation/libraryManager.mli] Erreur 2

This reverts commit c6f7ce50f9cead301db23922e99e38b7751bb156.

Change-Id: I3d42b54e47b4dbd8ea5da8583a14074f7770e8f8